 version: 2

 jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
 workflows:
   version: 2
   build: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - test
