 version: 2
 orbs:
  heroku: circleci/heroku@0.0.10
 jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
 workflows:
   version: 2
   build: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - test
       - deploy:
          requires:
            - test # only run if test has been sucsessful
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch

