 version: 2.1
 orbs:
  heroku: circleci/heroku@0.0.10
 jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
 workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch

