 version: 2
 orbs:
  heroku: circleci/heroku@0.0.10
 jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  heroku_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test # only deploy if tests have passed 
          filters:
            branches:
              only: master # only on master

